// THIS FILE WILL BE OVERWRITTEN BY DEV-C++!
// DO NOT EDIT!

#ifndef TICKERTAPE_PRIVATE_H
#define TICKERTAPE_PRIVATE_H

// VERSION DEFINITIONS
#define VER_STRING	"3.0.0.0"
#define VER_MAJOR	3
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"NMC TickerTape by Max Gurdziel"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"3.0"

#endif //TICKERTAPE_PRIVATE_H
